name: sheetsearch
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.2.1
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.6
      - fastapi==0.100.0
      - fpdf==1.7.2
      - frozenlist==1.4.0
      - h11==0.14.0
      - httptools==0.6.0
      - idna==3.4
      - multidict==6.0.4
      - openai==0.27.8
      - pillow==10.0.0
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - python-dotenv==1.0.0
      - python-magic==0.4.27
      - pyyaml==6.0.1
      - requests==2.31.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - urllib3==2.0.4
      - uvicorn==0.23.1
      - uvloop==0.17.0
      - watchfiles==0.19.0
      - websockets==11.0.3
      - yarl==1.9.2
